#!/bin/sh

# Post-process gnuplot SVG output:
# 1. replace bitmap logo with vector one (for smaller size and nicer look)
# 2. losslessly compress it to minimize download size

# load svg logo without svg element, drop indent and newlines
symbol_logo_bare="$(sed -E -e 's|</?svg.*>||g' -e 's/^ +//g' < ../logo/curl-symbol.svg | tr -d $'\n')"

# resize logo and move to center, set opacity
logo_embed="$(printf \
  '<g id="logo" opacity=".07" transform="matrix(0.564,0,0,0.564,672,274)">%s</g>' \
  "${symbol_logo_bare}")"

# replace image element generated by gnuplot svg export, with svg logo
cat stats.list | while read -r f; do
  # <image x='672.00' y='274.47' width='575.99' height='481.53' ...>
  sed -i.bak -E "s|\<image.+\>|${logo_embed}|g" "$f"
  rm -f "$f.bak"
done

# minimize SVG

if command -v scour >/dev/null 2>&1; then
  cat stats.list | while read -r f; do
    scour \
      --set-precision 3 \
      --strip-xml-prolog \
      --create-groups \
      --indent=none \
      --no-line-breaks \
      --enable-comment-stripping \
      --enable-id-stripping \
      --enable-viewboxing \
      --remove-metadata \
      --remove-descriptive-elements \
      --renderer-workaround \
      -i "$f" -o "$f.out"
    mv "$f.out" "$f"
  done
fi

if command -v svgo >/dev/null 2>&1; then
  cat stats.list | while read -r f; do
    svgo "$f"
  done
fi
