<span class="mirrorlinks">
Mirror:
#ifndef CURL_URL
<a href="http://curl.gds.tuwien.ac.at/">AT</a>
<a href="http://curl.planetmirror.com/">AU</a>
<a href="http://curl.mirror.at.stealer.net/">DE1</a>
<a href="http://curl.netmirror.org/">DE2</a>
<a href="http://curl.kgt.org/">DE3</a>
<a href="http://curl.mons-new-media.de/">DE4</a>
<a href="http://curl.mirroring.de/">DE5</a>
<a href="http://curl.cofman.dk/">DK</a>
<a href="http://curl.wildyou.net/">EE</a>
<a href="http://curl.mirror.internet.tp/">FR</a>
<a href="http://curl.tsuren.net/">RU</a>
<a href="http://curl.haxx.se/">SE</a>
<a href="http://curl.siamu.ac.th/">TH</a>
<a href="http://curl.cs.pu.edu.tw/">TW</a>
<a href="http://curl.mirrors.redwire.net/">US1</a>
<a href="http://curl.islandofpoker.com/">US2</a>
<a href="http://curl.109k.com/">US3</a>
<a href="http://curl.mirrormonster.com/">US4</a>
<a href="http://curl.mirrors.cyberservers.net/">US5</a>
<a href="http://curl.signal42.com/">US6</a>
<a href="http://curl.tolix.org/">US7</a>
<a href="http://curl.seekmeup.com/">US8</a>
<a href="http://curl.webhosting76.com/">US9</a>
#else
<a href="http://curl.gds.tuwien.ac.at/CURL_URL">AT</a>
<a href="http://curl.planetmirror.com/CURL_URL">AU</a>
<a href="http://curl.mirror.at.stealer.net/CURL_URL">DE1</a>
<a href="http://curl.netmirror.org/CURL_URL">DE2</a>
<a href="http://curl.kgt.org/CURL_URL">DE3</a>
<a href="http://curl.mons-new-media.de/CURL_URL">DE4</a>
<a href="http://curl.mirroring.de/CURL_URL">DE5</a>
<a href="http://curl.cofman.dk/CURL_URL">DK</a>
<a href="http://curl.wildyou.net/CURL_URL">EE</a>
<a href="http://curl.mirror.internet.tp/CURL_URL">FR</a>
<a href="http://curl.tsuren.net/CURL_URL">RU</a>
<a href="http://curl.haxx.se/CURL_URL">SE</a>
<a href="http://curl.siamu.ac.th/CURL_URL">TH</a>
<a href="http://curl.cs.pu.edu.tw/CURL_URL">TW</a>
<a href="http://curl.mirrors.redwire.net/CURL_URL">US1</a>
<a href="http://curl.islandofpoker.com/CURL_URL">US2</a>
<a href="http://curl.109k.com/CURL_URL">US3</a>
<a href="http://curl.mirrormonster.com/CURL_URL">US4</a>
<a href="http://curl.mirrors.cyberservers.net/CURL_URL">US5</a>
<a href="http://curl.signal42.com/CURL_URL">US6</a>
<a href="http://curl.tolix.org/CURL_URL">US7</a>
<a href="http://curl.seekmeup.com/CURL_URL">US8</a>
<a href="http://curl.webhosting76.com/CURL_URL">US9</a>
#endif
</span>
