<div class="relatedbox">
<b>Related:</b>
<br><a href="audits.html">Audits</a>
<br><a href="/docs/bugbounty.html">Bug Bounty</a>
<br><a href="/ch/">Changelog</a>
<br><a href="security.html">curl CVEs</a>
#ifdef FLAWCVE
<br><a href="FLAWCVE.json">JSON metadata</a>
#endif
#ifdef FLAWISSUE
<br><a href="FLAWISSUE">Original report</a>
#endif
<br><a href="/dev/vuln-disclosure.html">Vulnerability Disclosure</a>
<br><a href="vulnerabilities.html">Vulnerabilities Table</a>
</div>
